language: python
python:
  - "2.7"
  - "3.6"

before_install:
  - ./download_etcd.sh 2.3.7
  - pip install --upgrade setuptools

# command to install dependencies
install:
  - pip install coveralls
  - pip install coverage
  - pip install "dnspython>=1.13.0" "geventhttpclient>=1.3.1"
  - pip install mock nose gipc "pyOpenSSL>=0.14"

# command to run tests
script:
  PATH=$PATH:./bin nosetests --with-coverage --cover-package=etcd_gevent --logging-format="%(asctime)s %(levelname)s %(message)s" etcd_gevent

after_success:
  - coveralls
  - python setup.py sdist --formats=gztar
  - ./upload_twine.sh
# Add env var to detect it during build
env: TRAVIS=True
